package study.source.ch08;
class ExceptionEx9 
{
	public static void main(String[] args) {
		throw new RuntimeException();	// RuntimeException을 강제로 발생시킨다.
	}
}
